### ISSUE TITLE
Has anyone been seeing astronomical ask prices from the quote endpoint?

### ISSUE THREAD

**Issue by rclai** [sanko/Robinhood#43]
I've been getting ask prices of 199999.9900 for symbol VEA and some other Vanguard ETFs.

For example,
`https://api.robinhood.com/quotes/?symbols=VEA,VHT`

Is this normal? What do you make of this?

**Comment by JeffreyHyer** [comment]
Seems to be fixed now at least in the link you provided, or maybe it is intermittent. I haven't noticed anything off with the prices returned but I don't use the ask prices specifically, usually just the last trade price.

**Comment by sanko** [comment]
Yeah, I was planning on watching at/near open and double check because it was normal when I checked the endpoint linked too. ...and that was less than a minute after the issue was created. Maybe it's a capacity issue like the ones they had last year when the entire API would crumble; a random cache miss and 199999.9900 is a placeholder maybe.

**Comment by rclai** [comment]
Okay, I guess I can close it, but just wanted to share.
