### ISSUE TITLE
API Validity 

### ISSUE THREAD

**Issue by Taylor777** [sanko/Robinhood#51]
Trying to determine if this project has legs to go long term or is it more an academic exercise. Does Robinhood stand behind the effort or will it be shut off at some point.

**Comment by JeffreyHyer** [comment]
I can't speak to this project in particular but I don't think the Robinhood API is going anywhere anytime soon. They make reference to it on their website and are accepting applications from developers/partners to use it (so it's a semi-public API but not open to the public...yet) and I know they have several partners using it in third party applications so any changes will likely follow a standard release cycle involving deprecation/notification before complete removal.

You're biggest issue would be the eventual adoption of OAuth as the authentication scheme instead of username/password. If they switch to OAuth they can prevent unauthorized 3rd party use of the API.

I've been using the API for several months now in a side project and have not had any issues but I wouldn't use it beyond hobby projects at this point for fear of being crippled when things change.

**Comment by lynnwilliam** [comment]
I am also using it on a side project for risk management. Analyzing all my
past trades too see if I sell too early etc.
I've noticed that using the web calls is very very slow, compared to the
Robinhood app.
So there must be 2 levels of service.

**Comment by sanko** [comment]
I generally ignore these sorts of questions because it's a slippery slope. I do not and cannot represent Robinhood. Their intentions are their prerogative.

Ill just leave it at this: They know who I am and they know the 3rd party projects exist but it's all unofficial. Only when someone has managed to profit (like creating a service that wraps the API and then charges users for access) have they been known to get their legal department involved.

Recently, for various reasons, they've given me early access to get my opinion on Robinhood Web and I'm expecting a call from their Head of Communications tomorrow. I consider all of that a sign of good will but saying it's anything more than that would be jumping to conclusions.

...it's unofficial. And if they ask me, I'll take the documentation down without hesitation.

Re: OAuth

Right now, the official clients are using OAuth and an endpoint exists that can convert plain tokens to full oauth tokens. They've already set up scopes that'll allow people to block 3rd party clients from accessing (for example) banking related endpoints; they even have a full read-only scope. To me, that says they are expecting 3rd parties to use their API on behalf of users in the future... Even 3rd parties which will not have or need to be able to trade but might just want to see your watchlist.

**Comment by Taylor777** [comment]
Thanks for the information it would be nice to know what they (Robinhood Mkt) says about third party involvement. I absolutely can see the commercial pitfall here in particular anyone reselling there data.

If you could keep us updated on Robinhoods further development of an official API it would be much appreciated.
